[pytest]
testpaths = tests
markers =
    unittest: add a test as a unittest
    integration: add a test as an integration test
filterwarnings =
    error::pytest.PytestRemovedIn10Warning
    ignore:PyImport_ImportModuleNoBlock:DeprecationWarning:openjpeg.utils
    ignore:Invalid value for VR DT:UserWarning:pydicom.valuerep
    ignore:The length of the pixel data:UserWarning:pydicom.pixel_data_handlers.numpy_handler
    ignore:The odd length pixel data:UserWarning:pydicom.pixel_data_handlers.numpy_handler
